version: '3.8'

services:
  # CONTAINER 1: Chuyên làm nhiệm vụ phòng thủ (Giám sát & Phân tích)
  wpa3-monitor:
    build: .
    container_name: wpa3_defender
    network_mode: "host"
    privileged: true
    volumes:
      - ./data:/app/data
    environment:
      - INTERFACE=wlan0  # Card mạng dùng để nghe
    command: python3 src/monitor.py

  # CONTAINER 2: Chuyên làm nhiệm vụ tấn công (Kiểm thử)
  wpa3-attacker:
    build: .  # Dùng chung Image với container trên để tiết kiệm dung lượng
    container_name: wpa3_attacker
    network_mode: "host"
    privileged: true
    environment:
      - INTERFACE=wlan1  
    command: python3 src/simulator.py
    profiles: [ "attack" ] 